baseURL = "https://Navarathri.github.io/blog"
title = "たくあんは食べ物。"
languageCode = "ja"
theme = "hugo-theme-blueberry-detox"
publishDir = "docs"

googleAnalytics = "UA-159240537-2"
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  author = "tayu_tayu"
  SEOTitle = "たくあんは食べ物。 | tayu_tayu Blog"
  description = "@tayu_tayu"
  keyword = "tayu_tayu, Navarathri, travel"
  slogan = ""
  twitter_name = "tayu_tayu"

  image_404 = "img/404-bg.jpg"
  title_404 = "ページが見つかりません。 :("
  omit_categories = false

  # leancloud storage for page view counter
  page_view_conter = false
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = true
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  featured_tags = true
  featured_condition_size = 1


  # Include any custom CSS and/or JS files, url or relative to /static folder
  #custom_css = ["css/lightbox.css", "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css", "css/main.css"]
  #custom_js = ["js/lightbox.js", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js", "js/main.js"]

  [params.social]
  rss            = false
  email          = "youremail@gmail.com"
  #twitter       = "full profile url in twitter"
  # github         = ""

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]

[markup]
  [markup.tableOfContents]
    startLevel = 3
    endLevel = 5
    ordered = true
  [markup.highlight]
    style = "dracula"
