baseURL = "http://localhost:1313/"
languageCode = "ja-jp"
defaultContentLanguage = "ja-jp"
title = "たくあんは食べ物。"
theme = "zozo"
hasCJKLanguage = true                  # has chinese/japanese/korean ? 
summaryLength = 100
paginate = 5                         # shows the number of articles
enableEmoji = true
googleAnalytics = ""
disqusShortname = ""

pygmentsUseClasses = true
pygmentCodeFences = true
pygmentscodefencesguesssyntax = true

[author]
  name = "tayu_tayu"

[blackfriday]
  smartypants = false

[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Archive"
  weight = 20
  identifier = "archive"
  url = "/posts/"
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "About"
  weight = 40
  identifier = "about"
  url = "/about/"

[params]
  subTitle = "the site subtitle"
  footerSlogan = "#.Navarathri-"           
  keywords = ["Hugo","theme","zozo"]           
  description = "Hugo theme zozo example site."
  enableMathJax = true                         
  enableSummary = true                         
  mainSections = ["posts","post"]
  
[params.valine]
  enable = false
  appId = ""
  appKey = ""
  placeholder = " "
  visitor = true

# Your socail's url
[social]
#  github = " "
  twitter = " "
  facebook = " "
  weibo = " "
  instagram = " "

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
