theme = "hugo-theme-codex"
title = "たくあんは食べ物。"
languageCode = "jp"
baseURL = "https://www.tayu-tayu.me/"
copyright = "© {year}"
publishDir = "docs"

# Add your Disqus shortname here.
disqusShortname = "tayu_tayu"

# Add your Google Analytics identifier: UA-XXXXXXXX-X
# googleAnalytics = ""

# Optional params
[params]
  # 参考サイト：https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "2006-01-02"

  # Links to your social accounts, comment/uncomment as needed. Icons will be displayed for those specified.
  twitter = "https://twitter.com/tayu_tayu"
  YouTube = "https://www.youtube.com/channel/UCA7-eFymDhBVgq_Rdmo2RpA"

  # タイトルに表示するアイコンリスト
  # "Twitter", "GitHub", "Email", "Mastodon", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube"
  iconOrder = ["Twitter", "YouTube"]

  # Metadata for Twitter cards, defaults to params.twitter
  twitterSite = "@tayu_tayu"
  twitterAuthor = "@tayu_tayu"

  # Set to true to display page title in table of contents in blog posts.
  showPageTitleInTOC = false

# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
[markup]
  [markup.highlight]
    codeFences = false

  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

# Controls the navigation
[[menu.main]]
  identifier = "home"
  name = "home"
  title = "home"
  url = "/"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog"
