baseURL = "https://www.tayu-tayu.me"
title = "TAYU-TAYU.ME"
languageCode = "ja"
publishDir = "docs"

googleAnalytics = "UA-159240537-2"
preserveTaxonomyNam5es = true
paginate = 5

[params]
  author = "tayu_tayu"
  SEOTitle = "tayu-tayu.me"
  description = "日々の備忘録、雑記をまとめたサイトです。"
  twitter_name = "tayu_tayu"

  og_image = "images//thumbnails/default.png"

  image_404 = "img/404-bg.jpg"
  title_404 = "ページが見つかりません。 :("
  omit_categories = false

  # leancloud storage for page view counter
  page_view_conter = false
  leancloud_app_id = ""
  leancloud_app_key = ""

  featured_tags = true
  featured_condition_size = 1

[markup]
  [markup.tableOfContents]
    startLevel = 3
    endLevel = 5
    ordered = true
  [markup.highlight]
    style = "dracula"
